### ISSUE TITLE
Where is the dataset

### ISSUE THREAD

**Issue by maitian13** [andertadashi/density_sensitive_evolutionary_clustering#1]
I wander where to find the data which refered in code:
`self.columns = [
            'station',
            'date',
            'pressaomedia',
            'tempmaxima',
            'tempminima',
            'tempmedia',
            'radsolarmedia',
            'umidademedia',
            'velventomedio',
            'dirventomedio',
            'velrajadamedia',
            'precipitacao',
            'rajadamaxima'
        ]`

**Comment by andertadashi** [comment]
Hi @maitian13, I'm sorry but this data is not public.
